name: Build and Sign APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decode Keystore
      run: |
        echo ${{ secrets.ENCODED_KEYSTORE }} | base64 --decode > my-release-key.keystore
        echo "storeFile=my-release-key.keystore" >> local.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties

    - name: Build and Sign APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
