name: Test Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'  # 请根据你的项目需求选择合适的Java版本
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all -Dorg.gradle.java.home=$(readlink -f $(which javac) | sed "s:/bin/javac::") -Djava.security.egd=file:/dev/./urandom --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in $(find ~ -name "*.apk" -print); do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/
