name: Build and Sign APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 添加这个部分以支持手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build unsigned APK
      run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=/dev/null -Pandroid.injected.signing.store.password= -Pandroid.injected.signing.key.alias= -Pandroid.injected.signing.key.password=
    - name: Decode Keystore
      run: |
        echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > my-release-key.keystore
        echo "storeFile=my-release-key.keystore" >> local.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties
    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}
        zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-signed.apk
    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-signed.apk
